### ISSUE TITLE
Meet 'response=null' and 'Error add txt for domain:_acme-challenge' when issue with GoDaddy API

### ISSUE THREAD

**Issue by chuckyo** [Neilpang/acme.sh#1514]
acme version: `v2.7.9`

Hi I am using GoDaddy.com domain API to automatically issue cert, here is how I operated
```bash
export GD_Key="production key"
export GD_Secret="production secret"
# using staging just for escape 'Rate Limits of Let’s Encrypt'
acme.sh --issue --dns dns_gd -d mfun.io -d *.mfun.io --staging
```

Unfortunately, I get below output
```
[Fri Apr 13 10:23:27 UTC 2018] Using stage ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Apr 13 10:23:28 UTC 2018] Multi domain='DNS:mfun.io,DNS:*.mfun.io'
[Fri Apr 13 10:23:28 UTC 2018] Getting domain auth token for each domain
[Fri Apr 13 10:23:29 UTC 2018] Getting webroot for domain='mfun.io'
[Fri Apr 13 10:23:29 UTC 2018] Getting webroot for domain='*.mfun.io'
[Fri Apr 13 10:23:29 UTC 2018] Found domain api file: /root/.acme.sh/dnsapi/dns_gd.sh
[Fri Apr 13 10:23:32 UTC 2018] Adding record
[Fri Apr 13 10:23:33 UTC 2018] Add txt record error.
[Fri Apr 13 10:23:33 UTC 2018] null
[Fri Apr 13 10:23:33 UTC 2018] Error add txt for domain:_acme-challenge.mfun.io
[Fri Apr 13 10:23:33 UTC 2018] Please add '--debug' or '--log' to check more details.
[Fri Apr 13 10:23:33 UTC 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```

Below is output of `--debug 2`
```
[Fri Apr 13 09:47:08 UTC 2018] Lets find script dir.
[Fri Apr 13 09:47:08 UTC 2018] _SCRIPT_='/root/.acme.sh/acme.sh'
[Fri Apr 13 09:47:08 UTC 2018] _script='/root/.acme.sh/acme.sh'
[Fri Apr 13 09:47:08 UTC 2018] _script_home='/root/.acme.sh'
[Fri Apr 13 09:47:08 UTC 2018] Using config home:/root/.acme.sh
[Fri Apr 13 09:47:08 UTC 2018] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.7.9
[Fri Apr 13 09:47:08 UTC 2018] _main_domain='mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] _alt_domains='*.mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] Using config home:/root/.acme.sh
[Fri Apr 13 09:47:08 UTC 2018] Using stage ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Apr 13 09:47:08 UTC 2018] ACME_DIRECTORY='https://acme-staging-v02.api.letsencrypt.org/directory'
[Fri Apr 13 09:47:08 UTC 2018] _ACME_SERVER_HOST='acme-staging-v02.api.letsencrypt.org'
[Fri Apr 13 09:47:08 UTC 2018] DOMAIN_PATH='/root/.acme.sh/mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] 'dns_gd' does not contain 'dns'
[Fri Apr 13 09:47:08 UTC 2018] Using ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Apr 13 09:47:08 UTC 2018] _init api for server: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Apr 13 09:47:08 UTC 2018] GET
[Fri Apr 13 09:47:08 UTC 2018] url='https://acme-staging-v02.api.letsencrypt.org/directory'
[Fri Apr 13 09:47:08 UTC 2018] timeout=
[Fri Apr 13 09:47:08 UTC 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.U8T7OYNSFS  -g '
[Fri Apr 13 09:47:08 UTC 2018] ret='0'
[Fri Apr 13 09:47:08 UTC 2018] response='{
  "hqX_QJT59XE": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-staging-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org/docs/staging-environment/"
  },
  "newAccount": "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-staging-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert"
}'
[Fri Apr 13 09:47:08 UTC 2018] ACME_KEY_CHANGE='https://acme-staging-v02.api.letsencrypt.org/acme/key-change'
[Fri Apr 13 09:47:08 UTC 2018] ACME_NEW_AUTHZ
[Fri Apr 13 09:47:08 UTC 2018] ACME_NEW_ORDER='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Fri Apr 13 09:47:08 UTC 2018] ACME_NEW_ACCOUNT='https://acme-staging-v02.api.letsencrypt.org/acme/new-acct'
[Fri Apr 13 09:47:08 UTC 2018] ACME_REVOKE_CERT='https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert'
[Fri Apr 13 09:47:08 UTC 2018] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Fri Apr 13 09:47:08 UTC 2018] ACME_NEW_NONCE='https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce'
[Fri Apr 13 09:47:08 UTC 2018] ACME_VERSION='2'
[Fri Apr 13 09:47:08 UTC 2018] Le_NextRenewTime
[Fri Apr 13 09:47:08 UTC 2018] _on_before_issue
[Fri Apr 13 09:47:08 UTC 2018] _chk_main_domain='mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] _chk_alt_domains='*.mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] 'dns_gd' does not contain 'no'
[Fri Apr 13 09:47:08 UTC 2018] Le_LocalAddress
[Fri Apr 13 09:47:08 UTC 2018] d='mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] Check for domain='mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] _currentRoot='dns_gd'
[Fri Apr 13 09:47:08 UTC 2018] d='*.mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] Check for domain='*.mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] _currentRoot='dns_gd'
[Fri Apr 13 09:47:08 UTC 2018] d
[Fri Apr 13 09:47:08 UTC 2018] 'dns_gd' does not contain 'apache'
[Fri Apr 13 09:47:08 UTC 2018] _saved_account_key_hash='ajL1hpvsk/MaqOLvB/deuxENY0GVHnMTrNCMz1N+u4E='
[Fri Apr 13 09:47:08 UTC 2018] _saved_account_key_hash is not changed, skip register account.
[Fri Apr 13 09:47:08 UTC 2018] Read key length:
[Fri Apr 13 09:47:08 UTC 2018] _createcsr
[Fri Apr 13 09:47:08 UTC 2018] domain='mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] domainlist='*.mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] csrkey='/root/.acme.sh/mfun.io/mfun.io.key'
[Fri Apr 13 09:47:08 UTC 2018] csr='/root/.acme.sh/mfun.io/mfun.io.csr'
[Fri Apr 13 09:47:08 UTC 2018] csrconf='/root/.acme.sh/mfun.io/mfun.io.csr.conf'
[Fri Apr 13 09:47:08 UTC 2018] _is_idn_d='*.mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] _idn_temp
[Fri Apr 13 09:47:08 UTC 2018] domainlist='*.mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] Multi domain='DNS:mfun.io,DNS:*.mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] _is_idn_d='mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] _idn_temp
[Fri Apr 13 09:47:08 UTC 2018] _csr_cn='mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] Getting domain auth token for each domain
[Fri Apr 13 09:47:08 UTC 2018] d='*.mfun.io'
[Fri Apr 13 09:47:08 UTC 2018] d
[Fri Apr 13 09:47:08 UTC 2018] _identifiers='{"type":"dns","value":"mfun.io"},{"type":"dns","value":"*.mfun.io"}'
[Fri Apr 13 09:47:08 UTC 2018] url='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Fri Apr 13 09:47:08 UTC 2018] payload='{"identifiers": [{"type":"dns","value":"mfun.io"},{"type":"dns","value":"*.mfun.io"}]}'
[Fri Apr 13 09:47:08 UTC 2018] RSA key
[Fri Apr 13 09:47:08 UTC 2018] Get nonce. ACME_NEW_NONCE='https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce'
[Fri Apr 13 09:47:08 UTC 2018] HEAD
[Fri Apr 13 09:47:08 UTC 2018] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce'
[Fri Apr 13 09:47:08 UTC 2018] body
[Fri Apr 13 09:47:08 UTC 2018] _postContentType='application/jose+json'
[Fri Apr 13 09:47:08 UTC 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.3xDvjokhl3  -g '
[Fri Apr 13 09:47:09 UTC 2018] _ret='0'
[Fri Apr 13 09:47:09 UTC 2018] _headers='HTTP/1.1 204 No Content
Server: nginx
Replay-Nonce: KehY_r4jpSkdINIbs6xtsi4PSfLZKQfP7X1LS1dU0cI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 13 Apr 2018 09:47:09 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 13 Apr 2018 09:47:09 GMT
Connection: keep-alive
'
[Fri Apr 13 09:47:09 UTC 2018] _CACHED_NONCE='KehY_r4jpSkdINIbs6xtsi4PSfLZKQfP7X1LS1dU0cI'
[Fri Apr 13 09:47:09 UTC 2018] nonce='KehY_r4jpSkdINIbs6xtsi4PSfLZKQfP7X1LS1dU0cI'
[Fri Apr 13 09:47:09 UTC 2018] POST
[Fri Apr 13 09:47:09 UTC 2018] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/new-order'
[Fri Apr 13 09:47:09 UTC 2018] body='{"protected": "eyJub25jZSI6ICJLZWhZX3I0anBTa2RJTkliczZ4dHNpNFBTZkxaS1FmUDdYMUxTMWRVMGNJIiwgInVybCI6ICJodHRwczovL2FjbWUtc3RhZ2luZy12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciIsICJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC81OTEzMTU1In0", "payload": "eyJpZGVudGlmaWVycyI6IFt7InR5cGUiOiJkbnMiLCJ2YWx1ZSI6Im1mdW4uaW8ifSx7InR5cGUiOiJkbnMiLCJ2YWx1ZSI6IioubWZ1bi5pbyJ9XX0", "signature": "N-dx432Q5c54TIeXTicHZK68wLALojBMryAQWIhIzsEGGufHwqqKHRIjtgfudE-skQvKxj3CRJQ2a0bqZCZudW3vYjQT_C7LQNtEydBoPt9FScY6ivtwMwO2x_S_NfbilnANOqsHnGij1PDElsGYCGCYcrNFA-e90TzzEipnKVphRPb31Zvz3EGtaYgnPpIc9nUhYla0Txu-oN2KBY5SBrMvK7CohANfXlB1NK7CBW7MMtbvb09GsV0yFgCUy7BSjrIg0qdj4WkbtiRxCcsipL3y-jay0tonbtNbcGVkcIIljQQZlgTHUDQ_6DfOLQ0X_qufu57RiZaXX5oFLJSfXQ"}'
[Fri Apr 13 09:47:09 UTC 2018] _postContentType='application/jose+json'
[Fri Apr 13 09:47:09 UTC 2018] Http already initialized.
[Fri Apr 13 09:47:09 UTC 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.3xDvjokhl3  -g '
[Fri Apr 13 09:47:09 UTC 2018] _ret='0'
[Fri Apr 13 09:47:09 UTC 2018] original='{
  "status": "pending",
  "expires": "2018-04-20T09:47:09.372388128Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "*.mfun.io"
    },
    {
      "type": "dns",
      "value": "mfun.io"
    }
  ],
  "authorizations": [
    "https://acme-staging-v02.api.letsencrypt.org/acme/authz/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous",
    "https://acme-staging-v02.api.letsencrypt.org/acme/authz/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc"
  ],
  "finalize": "https://acme-staging-v02.api.letsencrypt.org/acme/finalize/5913155/377620"
}'
[Fri Apr 13 09:47:09 UTC 2018] responseHeaders='HTTP/1.1 201 Created
Server: nginx
Content-Type: application/json
Content-Length: 546
Boulder-Requester: 5913155
Location: https://acme-staging-v02.api.letsencrypt.org/acme/order/5913155/377620
Replay-Nonce: y7muBA16QvuXzzTWhS7iz98YKcsOogJxipPDeXROA68
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 13 Apr 2018 09:47:09 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 13 Apr 2018 09:47:09 GMT
Connection: keep-alive
'
[Fri Apr 13 09:47:09 UTC 2018] response='{"status":"pending","expires":"2018-04-20T09:47:09.372388128Z","identifiers":[{"type":"dns","value":"*.mfun.io"},{"type":"dns","value":"mfun.io"}],"authorizations":["https://acme-staging-v02.api.letsencrypt.org/acme/authz/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous","https://acme-staging-v02.api.letsencrypt.org/acme/authz/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc"],"finalize":"https://acme-staging-v02.api.letsencrypt.org/acme/finalize/5913155/377620"}'
[Fri Apr 13 09:47:09 UTC 2018] code='201'
[Fri Apr 13 09:47:09 UTC 2018] Le_OrderFinalize='https://acme-staging-v02.api.letsencrypt.org/acme/finalize/5913155/377620'
[Fri Apr 13 09:47:09 UTC 2018] _authorizations_seg='https://acme-staging-v02.api.letsencrypt.org/acme/authz/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous,https://acme-staging-v02.api.letsencrypt.org/acme/authz/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc'
[Fri Apr 13 09:47:09 UTC 2018] _authz_url='https://acme-staging-v02.api.letsencrypt.org/acme/authz/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous'
[Fri Apr 13 09:47:09 UTC 2018] GET
[Fri Apr 13 09:47:09 UTC 2018] url='https://acme-staging-v02.api.letsencrypt.org/acme/authz/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous'
[Fri Apr 13 09:47:09 UTC 2018] timeout=
[Fri Apr 13 09:47:09 UTC 2018] Http already initialized.
[Fri Apr 13 09:47:09 UTC 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.3xDvjokhl3  -g '
[Fri Apr 13 09:47:09 UTC 2018] ret='0'
[Fri Apr 13 09:47:09 UTC 2018] response='{"identifier":{"type":"dns","value":"mfun.io"},"status":"pending","expires":"2018-04-20T09:47:09Z","challenges":[{"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442","token":"urKbQYB8SYE6GBu7w2tpdpGheb3nzHfi23VTcCWb_yI"}],"wildcard": true}'
[Fri Apr 13 09:47:09 UTC 2018] _d='*.mfun.io'
[Fri Apr 13 09:47:09 UTC 2018] _authz_url='https://acme-staging-v02.api.letsencrypt.org/acme/authz/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc'
[Fri Apr 13 09:47:09 UTC 2018] GET
[Fri Apr 13 09:47:09 UTC 2018] url='https://acme-staging-v02.api.letsencrypt.org/acme/authz/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc'
[Fri Apr 13 09:47:09 UTC 2018] timeout=
[Fri Apr 13 09:47:09 UTC 2018] Http already initialized.
[Fri Apr 13 09:47:09 UTC 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.3xDvjokhl3  -g '
[Fri Apr 13 09:47:10 UTC 2018] ret='0'
[Fri Apr 13 09:47:10 UTC 2018] response='{"identifier":{"type":"dns","value":"mfun.io"},"status":"pending","expires":"2018-04-20T09:47:09Z","challenges":[{"type":"http-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438443","token":"kVb2sKy9UVl3b9pklQ61Bi0UR98ldvZGtMVgv3nVg8g"},{"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444","token":"4wWKEtvyqG-llhR6VqWZwdWLr1RLEiI_PK6ZBP8HHXc"}]}'
[Fri Apr 13 09:47:10 UTC 2018] _d='mfun.io'
[Fri Apr 13 09:47:10 UTC 2018] _authorizations_map='mfun.io,{"identifier":{"type":"dns","value":"mfun.io"},"status":"pending","expires":"2018-04-20T09:47:09Z","challenges":[{"type":"http-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438443","token":"kVb2sKy9UVl3b9pklQ61Bi0UR98ldvZGtMVgv3nVg8g"},{"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444","token":"4wWKEtvyqG-llhR6VqWZwdWLr1RLEiI_PK6ZBP8HHXc"}]}
*.mfun.io,{"identifier":{"type":"dns","value":"mfun.io"},"status":"pending","expires":"2018-04-20T09:47:09Z","challenges":[{"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442","token":"urKbQYB8SYE6GBu7w2tpdpGheb3nzHfi23VTcCWb_yI"}],"wildcard": true}
'
[Fri Apr 13 09:47:10 UTC 2018] d='mfun.io'
[Fri Apr 13 09:47:10 UTC 2018] Getting webroot for domain='mfun.io'
[Fri Apr 13 09:47:10 UTC 2018] _w='dns_gd'
[Fri Apr 13 09:47:10 UTC 2018] _currentRoot='dns_gd'
[Fri Apr 13 09:47:10 UTC 2018] response='{"identifier":{"type":"dns","value":"mfun.io"},"status":"pending","expires":"2018-04-20T09:47:09Z","challenges":[{"type":"http-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438443","token":"kVb2sKy9UVl3b9pklQ61Bi0UR98ldvZGtMVgv3nVg8g"},{"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444","token":"4wWKEtvyqG-llhR6VqWZwdWLr1RLEiI_PK6ZBP8HHXc"}]}'
[Fri Apr 13 09:47:10 UTC 2018] entry='"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444","token":"4wWKEtvyqG-llhR6VqWZwdWLr1RLEiI_PK6ZBP8HHXc"'
[Fri Apr 13 09:47:10 UTC 2018] token='4wWKEtvyqG-llhR6VqWZwdWLr1RLEiI_PK6ZBP8HHXc'
[Fri Apr 13 09:47:10 UTC 2018] uri='https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444'
[Fri Apr 13 09:47:10 UTC 2018] keyauthorization='4wWKEtvyqG-llhR6VqWZwdWLr1RLEiI_PK6ZBP8HHXc.VW966EoEjiFkKZ6f7hLTj3lUNVn3DwiZxTZjo4UNzfU'
[Fri Apr 13 09:47:10 UTC 2018] dvlist='mfun.io#4wWKEtvyqG-llhR6VqWZwdWLr1RLEiI_PK6ZBP8HHXc.VW966EoEjiFkKZ6f7hLTj3lUNVn3DwiZxTZjo4UNzfU#https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444#dns-01#dns_gd'
[Fri Apr 13 09:47:10 UTC 2018] d='*.mfun.io'
[Fri Apr 13 09:47:10 UTC 2018] Getting webroot for domain='*.mfun.io'
[Fri Apr 13 09:47:10 UTC 2018] _w='dns_gd'
[Fri Apr 13 09:47:10 UTC 2018] _currentRoot='dns_gd'
[Fri Apr 13 09:47:10 UTC 2018] response='{"identifier":{"type":"dns","value":"mfun.io"},"status":"pending","expires":"2018-04-20T09:47:09Z","challenges":[{"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442","token":"urKbQYB8SYE6GBu7w2tpdpGheb3nzHfi23VTcCWb_yI"}],"wildcard": true}'
[Fri Apr 13 09:47:10 UTC 2018] entry='"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442","token":"urKbQYB8SYE6GBu7w2tpdpGheb3nzHfi23VTcCWb_yI"'
[Fri Apr 13 09:47:10 UTC 2018] token='urKbQYB8SYE6GBu7w2tpdpGheb3nzHfi23VTcCWb_yI'
[Fri Apr 13 09:47:10 UTC 2018] uri='https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442'
[Fri Apr 13 09:47:10 UTC 2018] keyauthorization='urKbQYB8SYE6GBu7w2tpdpGheb3nzHfi23VTcCWb_yI.VW966EoEjiFkKZ6f7hLTj3lUNVn3DwiZxTZjo4UNzfU'
[Fri Apr 13 09:47:10 UTC 2018] dvlist='*.mfun.io#urKbQYB8SYE6GBu7w2tpdpGheb3nzHfi23VTcCWb_yI.VW966EoEjiFkKZ6f7hLTj3lUNVn3DwiZxTZjo4UNzfU#https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442#dns-01#dns_gd'
[Fri Apr 13 09:47:10 UTC 2018] d
[Fri Apr 13 09:47:10 UTC 2018] vlist='mfun.io#4wWKEtvyqG-llhR6VqWZwdWLr1RLEiI_PK6ZBP8HHXc.VW966EoEjiFkKZ6f7hLTj3lUNVn3DwiZxTZjo4UNzfU#https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444#dns-01#dns_gd,*.mfun.io#urKbQYB8SYE6GBu7w2tpdpGheb3nzHfi23VTcCWb_yI.VW966EoEjiFkKZ6f7hLTj3lUNVn3DwiZxTZjo4UNzfU#https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442#dns-01#dns_gd,'
[Fri Apr 13 09:47:10 UTC 2018] d='mfun.io'
[Fri Apr 13 09:47:10 UTC 2018] _d_alias
[Fri Apr 13 09:47:10 UTC 2018] txtdomain='_acme-challenge.mfun.io'
[Fri Apr 13 09:47:10 UTC 2018] txt='Dao9-D_7apwQB8lVPugiYihLoGhRYevqFto7WdZiI_M'
[Fri Apr 13 09:47:10 UTC 2018] d_api='/root/.acme.sh/dnsapi/dns_gd.sh'
[Fri Apr 13 09:47:10 UTC 2018] Found domain api file: /root/.acme.sh/dnsapi/dns_gd.sh
[Fri Apr 13 09:47:10 UTC 2018] First detect the root zone
[Fri Apr 13 09:47:10 UTC 2018] domains/mfun.io
[Fri Apr 13 09:47:10 UTC 2018] GET
[Fri Apr 13 09:47:10 UTC 2018] url='https://api.godaddy.com/v1/domains/mfun.io'
[Fri Apr 13 09:47:10 UTC 2018] timeout=
[Fri Apr 13 09:47:10 UTC 2018] Http already initialized.
[Fri Apr 13 09:47:10 UTC 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.3xDvjokhl3  -g '
[Fri Apr 13 09:47:12 UTC 2018] ret='0'
[Fri Apr 13 09:47:12 UTC 2018] response='{"domainId":262793158,"domain":"mfun.io","status":"ACTIVE","expires":"2019-02-26T09:40:25Z","expirationProtected":false,"holdRegistrar":false,"locked":true,"privacy":false,"renewAuto":true,"renewable":true,"renewDeadline":"2019-04-12T02:40:19Z","transferProtected":false,"createdAt":"2018-02-26T09:40:25Z","transferAwayEligibleAt":"2018-04-27T09:40:25Z","authCode":"3UK1JE8%/?0v4vdB","nameServers":["ns17.domaincontrol.com","ns18.domaincontrol.com"],"contactRegistrant":{"nameFirst":"Akasanet Bumi","nameLast":"Nusantara","organization":"PT Akasanet Bumi Nusantara","email":"akasanet.abn@gmail.com","phone":"+62.217398902","fax":"","addressMailing":{"address1":"Jl. Kyai Maja No.1, Kebayoran Baru","address2":"","city":"Jakarta Selatan","state":"DKI Jakarta","postalCode":"12120","country":"ID"}},"contactBilling":{"nameFirst":"Akasanet Bumi","nameLast":"Nusantara","organization":"PT Akasanet Bumi Nusantara","email":"akasanet.abn@gmail.com","phone":"+62.217398902","fax":"","addressMailing":{"address1":"Jl. Kyai Maja No.1, Kebayoran Baru","address2":"","city":"Jakarta Selatan","state":"DKI Jakarta","postalCode":"12120","country":"ID"}},"contactAdmin":{"nameFirst":"Akasanet Bumi","nameLast":"Nusantara","organization":"PT Akasanet Bumi Nusantara","email":"akasanet.abn@gmail.com","phone":"+62.217398902","fax":"","addressMailing":{"address1":"Jl. Kyai Maja No.1, Kebayoran Baru","address2":"","city":"Jakarta Selatan","state":"DKI Jakarta","postalCode":"12120","country":"ID"}},"contactTech":{"nameFirst":"Akasanet Bumi","nameLast":"Nusantara","organization":"PT Akasanet Bumi Nusantara","email":"akasanet.abn@gmail.com","phone":"+62.217398902","fax":"","addressMailing":{"address1":"Jl. Kyai Maja No.1, Kebayoran Baru","address2":"","city":"Jakarta Selatan","state":"DKI Jakarta","postalCode":"12120","country":"ID"}}}'
[Fri Apr 13 09:47:12 UTC 2018] _sub_domain='_acme-challenge'
[Fri Apr 13 09:47:12 UTC 2018] _domain='mfun.io'
[Fri Apr 13 09:47:12 UTC 2018] Getting existing records
[Fri Apr 13 09:47:12 UTC 2018] domains/mfun.io/records/TXT/_acme-challenge
[Fri Apr 13 09:47:12 UTC 2018] GET
[Fri Apr 13 09:47:12 UTC 2018] url='https://api.godaddy.com/v1/domains/mfun.io/records/TXT/_acme-challenge'
[Fri Apr 13 09:47:12 UTC 2018] timeout=
[Fri Apr 13 09:47:12 UTC 2018] Http already initialized.
[Fri Apr 13 09:47:12 UTC 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.3xDvjokhl3  -g '
[Fri Apr 13 09:47:12 UTC 2018] ret='0'
[Fri Apr 13 09:47:12 UTC 2018] response='[]'
[Fri Apr 13 09:47:12 UTC 2018] _add_data='{"data":"Dao9-D_7apwQB8lVPugiYihLoGhRYevqFto7WdZiI_M"}'
[Fri Apr 13 09:47:12 UTC 2018] Adding record
[Fri Apr 13 09:47:12 UTC 2018] domains/mfun.io/records/TXT/_acme-challenge
[Fri Apr 13 09:47:12 UTC 2018] data='[{"data":"Dao9-D_7apwQB8lVPugiYihLoGhRYevqFto7WdZiI_M"}]'
[Fri Apr 13 09:47:12 UTC 2018] PUT
[Fri Apr 13 09:47:12 UTC 2018] _post_url='https://api.godaddy.com/v1/domains/mfun.io/records/TXT/_acme-challenge'
[Fri Apr 13 09:47:12 UTC 2018] body='[{"data":"Dao9-D_7apwQB8lVPugiYihLoGhRYevqFto7WdZiI_M"}]'
[Fri Apr 13 09:47:12 UTC 2018] _postContentType
[Fri Apr 13 09:47:12 UTC 2018] Http already initialized.
[Fri Apr 13 09:47:12 UTC 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.3xDvjokhl3  -g '
[Fri Apr 13 09:47:13 UTC 2018] _ret='0'
[Fri Apr 13 09:47:13 UTC 2018] response='null'
[Fri Apr 13 09:47:13 UTC 2018] Add txt record error.
[Fri Apr 13 09:47:13 UTC 2018] null
[Fri Apr 13 09:47:13 UTC 2018] Error add txt for domain:_acme-challenge.mfun.io
[Fri Apr 13 09:47:13 UTC 2018] pid
[Fri Apr 13 09:47:13 UTC 2018] No need to restore nginx, skip.
[Fri Apr 13 09:47:13 UTC 2018] _clearupdns
[Fri Apr 13 09:47:13 UTC 2018] skip dns.
[Fri Apr 13 09:47:13 UTC 2018] _on_issue_err
[Fri Apr 13 09:47:13 UTC 2018] Please add '--debug' or '--log' to check more details.
[Fri Apr 13 09:47:13 UTC 2018] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Fri Apr 13 09:47:13 UTC 2018] _chk_vlist='mfun.io#4wWKEtvyqG-llhR6VqWZwdWLr1RLEiI_PK6ZBP8HHXc.VW966EoEjiFkKZ6f7hLTj3lUNVn3DwiZxTZjo4UNzfU#https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444#dns-01#dns_gd,*.mfun.io#urKbQYB8SYE6GBu7w2tpdpGheb3nzHfi23VTcCWb_yI.VW966EoEjiFkKZ6f7hLTj3lUNVn3DwiZxTZjo4UNzfU#https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442#dns-01#dns_gd,'
[Fri Apr 13 09:47:13 UTC 2018] start to deactivate authz
[Fri Apr 13 09:47:13 UTC 2018] tigger domain validation.
[Fri Apr 13 09:47:13 UTC 2018] _t_url='https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444'
[Fri Apr 13 09:47:13 UTC 2018] _t_key_authz='4wWKEtvyqG-llhR6VqWZwdWLr1RLEiI_PK6ZBP8HHXc.VW966EoEjiFkKZ6f7hLTj3lUNVn3DwiZxTZjo4UNzfU'
[Fri Apr 13 09:47:13 UTC 2018] url='https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444'
[Fri Apr 13 09:47:13 UTC 2018] payload='{"keyAuthorization": "4wWKEtvyqG-llhR6VqWZwdWLr1RLEiI_PK6ZBP8HHXc.VW966EoEjiFkKZ6f7hLTj3lUNVn3DwiZxTZjo4UNzfU"}'
[Fri Apr 13 09:47:13 UTC 2018] Use cached jwk for file: /root/.acme.sh/ca/acme-staging-v02.api.letsencrypt.org/account.key
[Fri Apr 13 09:47:13 UTC 2018] Use _CACHED_NONCE='y7muBA16QvuXzzTWhS7iz98YKcsOogJxipPDeXROA68'
[Fri Apr 13 09:47:13 UTC 2018] nonce='y7muBA16QvuXzzTWhS7iz98YKcsOogJxipPDeXROA68'
[Fri Apr 13 09:47:13 UTC 2018] POST
[Fri Apr 13 09:47:13 UTC 2018] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444'
[Fri Apr 13 09:47:13 UTC 2018] body='{"protected": "eyJub25jZSI6ICJ5N211QkExNlF2dVh6elRXaFM3aXo5OFlLY3NPb2dKeGlwUERlWFJPQTY4IiwgInVybCI6ICJodHRwczovL2FjbWUtc3RhZ2luZy12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsZW5nZS9tMUZQdlVYM1pLaDJVWUJHUHU3U1A3N2NhZ1d2c0d4dnFHcUJpREY5eWRjLzExNzQzODQ0NCIsICJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC81OTEzMTU1In0", "payload": "eyJrZXlBdXRob3JpemF0aW9uIjogIjR3V0tFdHZ5cUctbGxoUjZWcVdad2RXTHIxUkxFaUlfUEs2WkJQOEhIWGMuVlc5NjZFb0VqaUZrS1o2ZjdoTFRqM2xVTlZuM0R3aVp4VFpqbzRVTnpmVSJ9", "signature": "LBWuJ9Z--N88oxuH91sDdmWlHJu8eD-8UNzSiy2wvosK2xOn_lzo4oG80MMqxOfVNMjB7OvcKL7gddRMRF-Co0_FHzPpSnORclsFVbNx3LxwZry8P_o2i1f3xL2mxws7iIuI2xQQntmGUAA1ILPZTPn_FBYIkLzCq2Ek8xWCU2sEK1EI_thOsLZCkqoHXoA8aOb60WmL7GmfcAeXdIEdaKB5BLz-C6FwLWBi-Ha5QdfxzaqSkvoA0-QQipjn6hA6e76WG5GMgOY98ghyF4Y1gtXiS9YnwmVYQ0By859inCyaqzWCcxA8gWUtVMo3DszioLSnnBbwnWHyzfuQ2eL_Cg"}'
[Fri Apr 13 09:47:13 UTC 2018] _postContentType='application/jose+json'
[Fri Apr 13 09:47:13 UTC 2018] Http already initialized.
[Fri Apr 13 09:47:13 UTC 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.3xDvjokhl3  -g '
[Fri Apr 13 09:47:13 UTC 2018] _ret='0'
[Fri Apr 13 09:47:13 UTC 2018] original='{
  "type": "dns-01",
  "status": "pending",
  "url": "https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444",
  "token": "4wWKEtvyqG-llhR6VqWZwdWLr1RLEiI_PK6ZBP8HHXc"
}'
[Fri Apr 13 09:47:13 UTC 2018] responseHeaders='HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 229
Boulder-Requester: 5913155
Link: <https://acme-staging-v02.api.letsencrypt.org/acme/authz/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc>;rel="up"
Location: https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444
Replay-Nonce: iwcxpTFUjXPNWs0E7G5bPow3QEFLOUIIPfmLK6h7LL4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 13 Apr 2018 09:47:13 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 13 Apr 2018 09:47:13 GMT
Connection: keep-alive
'
[Fri Apr 13 09:47:13 UTC 2018] response='{"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/m1FPvUX3ZKh2UYBGPu7SP77cagWvsGxvqGqBiDF9ydc/117438444","token":"4wWKEtvyqG-llhR6VqWZwdWLr1RLEiI_PK6ZBP8HHXc"}'
[Fri Apr 13 09:47:13 UTC 2018] code='200'
[Fri Apr 13 09:47:13 UTC 2018] tigger domain validation.
[Fri Apr 13 09:47:13 UTC 2018] _t_url='https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442'
[Fri Apr 13 09:47:13 UTC 2018] _t_key_authz='urKbQYB8SYE6GBu7w2tpdpGheb3nzHfi23VTcCWb_yI.VW966EoEjiFkKZ6f7hLTj3lUNVn3DwiZxTZjo4UNzfU'
[Fri Apr 13 09:47:13 UTC 2018] url='https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442'
[Fri Apr 13 09:47:13 UTC 2018] payload='{"keyAuthorization": "urKbQYB8SYE6GBu7w2tpdpGheb3nzHfi23VTcCWb_yI.VW966EoEjiFkKZ6f7hLTj3lUNVn3DwiZxTZjo4UNzfU"}'
[Fri Apr 13 09:47:13 UTC 2018] Use cached jwk for file: /root/.acme.sh/ca/acme-staging-v02.api.letsencrypt.org/account.key
[Fri Apr 13 09:47:13 UTC 2018] Use _CACHED_NONCE='iwcxpTFUjXPNWs0E7G5bPow3QEFLOUIIPfmLK6h7LL4'
[Fri Apr 13 09:47:13 UTC 2018] nonce='iwcxpTFUjXPNWs0E7G5bPow3QEFLOUIIPfmLK6h7LL4'
[Fri Apr 13 09:47:13 UTC 2018] POST
[Fri Apr 13 09:47:13 UTC 2018] _post_url='https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442'
[Fri Apr 13 09:47:13 UTC 2018] body='{"protected": "eyJub25jZSI6ICJpd2N4cFRGVWpYUE5XczBFN0c1YlBvdzNRRUZMT1VJSVBmbUxLNmg3TEw0IiwgInVybCI6ICJodHRwczovL2FjbWUtc3RhZ2luZy12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsZW5nZS9TbDNNeWVoZDI3RGg4WGVKM2s0WEtOUVVFWExaOUtGM3NHTGt2b3pfb3VzLzExNzQzODQ0MiIsICJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC81OTEzMTU1In0", "payload": "eyJrZXlBdXRob3JpemF0aW9uIjogInVyS2JRWUI4U1lFNkdCdTd3MnRwZHBHaGViM256SGZpMjNWVGNDV2JfeUkuVlc5NjZFb0VqaUZrS1o2ZjdoTFRqM2xVTlZuM0R3aVp4VFpqbzRVTnpmVSJ9", "signature": "RZs221x_KycQWQH-8rNLs0LMlWw18E3FbJZSXZFhJKV-0PX1KxrVNhSX8hghfNWUsZP91Pv7mOot5PNHwk0qLycpKI7uK9ANcCHtZwTtcvgqZ5jHIH78h-07XiO3i_eK-lg0g_iuXks6-M4f2iEMwF9S8OqpFZEIqb8FluCYoXyarEoOD2zYtS3xvZSuB2Im-3xc3DJtUVkOlqAVGPKsie93TV_7ImsALhHuy08XlsCjEm1ps2qLfZvCI2uS3ceexUa7_JhouZepfG2IX53JkAA7IWzwy-I5Pqsbr5w9gu3CagxWovb5XuBW2bwo6FuLqJ03hgXmJG46_ECq3M2tRA"}'
[Fri Apr 13 09:47:13 UTC 2018] _postContentType='application/jose+json'
[Fri Apr 13 09:47:13 UTC 2018] Http already initialized.
[Fri Apr 13 09:47:13 UTC 2018] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.3xDvjokhl3  -g '
[Fri Apr 13 09:47:14 UTC 2018] _ret='0'
[Fri Apr 13 09:47:14 UTC 2018] original='{
  "type": "dns-01",
  "status": "pending",
  "url": "https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442",
  "token": "urKbQYB8SYE6GBu7w2tpdpGheb3nzHfi23VTcCWb_yI"
}'
[Fri Apr 13 09:47:14 UTC 2018] responseHeaders='HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 229
Boulder-Requester: 5913155
Link: <https://acme-staging-v02.api.letsencrypt.org/acme/authz/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous>;rel="up"
Location: https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442
Replay-Nonce: 26TpeKcTMFSUFgoUuLia7sgHvazlxfzmi4I7x5PeasU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 13 Apr 2018 09:47:14 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 13 Apr 2018 09:47:14 GMT
Connection: keep-alive
'
[Fri Apr 13 09:47:14 UTC 2018] response='{"type":"dns-01","status":"pending","url":"https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Sl3Myehd27Dh8XeJ3k4XKNQUEXLZ9KF3sGLkvoz_ous/117438442","token":"urKbQYB8SYE6GBu7w2tpdpGheb3nzHfi23VTcCWb_yI"}'
[Fri Apr 13 09:47:14 UTC 2018] code='200'
[Fri Apr 13 09:47:14 UTC 2018] socat doesn't exists.
[Fri Apr 13 09:47:14 UTC 2018] Diagnosis versions:
openssl:openssl
OpenSSL 1.0.2h  3 May 2016
apache:
apache doesn't exists.
nginx:
nginx version: nginx/1.12.2
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-mail=dynamic --with-mail_ssl_module --add-dynamic-module=/build/nginx-6T6rDv/nginx-1.12.2/debian/modules/nginx-auth-pam --add-dynamic-module=/build/nginx-6T6rDv/nginx-1.12.2/debian/modules/nginx-dav-ext-module --add-dynamic-module=/build/nginx-6T6rDv/nginx-1.12.2/debian/modules/nginx-echo --add-dynamic-module=/build/nginx-6T6rDv/nginx-1.12.2/debian/modules/nginx-upstream-fair --add-dynamic-module=/build/nginx-6T6rDv/nginx-1.12.2/debian/modules/ngx_http_substitutions_filter_module
socat:
```

When I check console of GoDaddy, I found there was `TXT _acme-challenge Dao9-D_7apwQB8lVPugiYihLoGhRYevqFto7WdZiI_M` generated, but when I tried `host -t txt mfun.io` I only get below output
```
mfun.io descriptive text "google-site-verification=4Fu***"
mfun.io descriptive text "v=spf1 include:_spf.google.com ~all"
```

I read the log but didn't figure out the issue, thanks in advance for help.

**Comment by ferranbonas** [comment]
Same error: https://github.com/Neilpang/acme.sh/issues/1512

**Comment by Neilpang** [comment]
godaddy changed its api.
fixed, please try with the latest code.

**Comment by unmec** [comment]
I ran ```acme.sh --upgrade``` but it appears that the same error still occurs with ```Add txt record error.```

When I look through the log I noticed this as well:

```
response='{"code":"NOT_FOUND","message":"Domain www.dummydomain.com not found for shopper","name":"ApiError"}'
```
In GoDaddy's DNS, there are multiples DNS entries with ```_acme-challenge.www``` so I assume that acme.sh has access to GD account but the interaction with new API failed in some way.
